name: Gerar APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Gerar APK
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: stable
          cache: true

      - name: Criar estrutura Android
        run: |
          flutter create --platforms=android .

      - name: Instalar dependências
        run: |
          flutter pub get

      - name: Desativar R8
        run: |
          if [ -f android/app/build.gradle.kts ]; then
            sed -i 's/isMinifyEnabled = true/isMinifyEnabled = false/g' android/app/build.gradle.kts
            sed -i 's/isShrinkResources = true/isShrinkResources = false/g' android/app/build.gradle.kts
          fi

          if [ -f android/app/build.gradle ]; then
            sed -i 's/minifyEnabled true/minifyEnabled false/g' android/app/build.gradle
            sed -i 's/shrinkResources true/shrinkResources false/g' android/app/build.gradle
          fi

      - name: Limpar projeto
        run: |
          flutter clean
          flutter pub get

      - name: Compilar APK
        run: |
          flutter build apk --release --no-shrink

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: aplicativo-shopee
          path: build/app/outputs/flutter-apk/app-release.apk
